name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip poetry

    - name: Test with nosetests
      run: |
        poetry run pytest --cov=pycvesearch tests/tests.py

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
